In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
credit_data=pd.read_csv("uci_credit_card.csv")
credit_data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [13]:
credit_data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

In [14]:
input_data=credit_data[['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0','BILL_AMT1','PAY_AMT1']]
input_data=tf.constant(input_data, tf.float32)
print(input_data)

tf.Tensor(
[[ 2.0000e+04  2.0000e+00  2.0000e+00 ...  2.0000e+00  3.9130e+03
   0.0000e+00]
 [ 1.2000e+05  2.0000e+00  2.0000e+00 ... -1.0000e+00  2.6820e+03
   0.0000e+00]
 [ 9.0000e+04  2.0000e+00  2.0000e+00 ...  0.0000e+00  2.9239e+04
   1.5180e+03]
 ...
 [ 3.0000e+04  1.0000e+00  2.0000e+00 ...  4.0000e+00  3.5650e+03
   0.0000e+00]
 [ 8.0000e+04  1.0000e+00  3.0000e+00 ...  1.0000e+00 -1.6450e+03
   8.5900e+04]
 [ 5.0000e+04  1.0000e+00  2.0000e+00 ...  0.0000e+00  4.7929e+04
   2.0780e+03]], shape=(30000, 8), dtype=float32)


In [27]:
# Define the first dense layer
dense1 = tf.keras.layers.Dense(5, activation='relu')(input_data)

# Define a dense layer with 3 output nodes
dense2 = tf.keras.layers.Dense(3, activation='relu')(dense1)

# Define a dense layer with 1 output node
predictions = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print('\n shape of dense1: ', dense1.shape)
print('\n shape of dense2: ', dense2.shape)
print('\n shape of predictions: ', predictions.shape)


 shape of dense1:  (30000, 5)

 shape of dense2:  (30000, 3)

 shape of predictions:  (30000, 1)


In [26]:
# Define the first dense layer
dense1 = tf.keras.layers.Dense(5)(input_data)
dense1=tf.keras.layers.Activation('relu')(dense1)

# Define a dense layer with 3 output nodes
dense2 = tf.keras.layers.Dense(3, activation='relu')(dense1)

# Define a dense layer with 1 output node
predictions = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

In [19]:
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])
print(x1)

tf.Tensor(
[[[-0.6970166   1.0116735   0.10525291  0.5258683 ]
  [ 0.38121694  0.5901393   1.39418    -0.2867037 ]
  [-0.04971446 -0.5718816  -0.6477137   0.16433775]]

 [[ 1.5235674   0.7954769  -0.21502861 -2.0831382 ]
  [ 1.4538095   0.644875    0.29210842  1.9168937 ]
  [-0.41998354  3.2115664  -0.4153921  -0.14810681]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
# Create a model
def model(input_data):
    # Define the first dense layer
    dense1 = tf.keras.layers.Dense(5)(input_data)
    print
    dense1=tf.keras.layers.Activation('relu')(dense1)
    # Define a dense layer with 3 output nodes
    dense2 = tf.keras.layers.Dense(3, activation='relu')(dense1)
    # Define a dense layer with 1 output node
    predictions = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)
    return predictions

def loss():


In [30]:
# Import required packages
import tensorflow as tf
import keras
from keras.layers import Dense
#Create a sequential Model
model=keras.models.Sequential()
#Add input layer
model.add(Dense(5, input_shape=(2,), activation="relu"))
#Add Hidden Layer
model.add(Dense(3, activation="relu"))
#Add output layer
model.add(Dense(1, activation="sigmoid"))
#print model 
print(model.summary())



Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 5)                 15        
                                                                 
 dense_21 (Dense)            (None, 3)                 18        
                                                                 
 dense_22 (Dense)            (None, 1)                 4         
                                                                 
Total params: 37
Trainable params: 37
Non-trainable params: 0
_________________________________________________________________
None
