In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
credit_data=pd.read_csv("uci_credit_card.csv")
credit_data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [4]:
credit_data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

In [5]:
input_data=np.array(credit_data[['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0','BILL_AMT1','PAY_AMT1']])
#input_data=tf.constant(input_data, tf.float32)
label=np.array(credit_data['default.payment.next.month'])
#label=tf.constant(label, tf.float32)
print(type(input_data))

<class 'numpy.ndarray'>


In [6]:
print(input_data.shape)

(30000, 8)


In [27]:
# Define the first dense layer
dense1 = tf.keras.layers.Dense(5, activation='relu')(input_data)

# Define a dense layer with 3 output nodes
dense2 = tf.keras.layers.Dense(3, activation='relu')(dense1)

# Define a dense layer with 1 output node
predictions = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print('\n shape of dense1: ', dense1.shape)
print('\n shape of dense2: ', dense2.shape)
print('\n shape of predictions: ', predictions.shape)


 shape of dense1:  (30000, 5)

 shape of dense2:  (30000, 3)

 shape of predictions:  (30000, 1)


In [26]:
# Define the first dense layer
dense1 = tf.keras.layers.Dense(5)(input_data)
dense1=tf.keras.layers.Activation('relu')(dense1)

# Define a dense layer with 3 output nodes
dense2 = tf.keras.layers.Dense(3, activation='relu')(dense1)

# Define a dense layer with 1 output node
predictions = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

In [19]:
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])
print(x1)

tf.Tensor(
[[[-0.6970166   1.0116735   0.10525291  0.5258683 ]
  [ 0.38121694  0.5901393   1.39418    -0.2867037 ]
  [-0.04971446 -0.5718816  -0.6477137   0.16433775]]

 [[ 1.5235674   0.7954769  -0.21502861 -2.0831382 ]
  [ 1.4538095   0.644875    0.29210842  1.9168937 ]
  [-0.41998354  3.2115664  -0.4153921  -0.14810681]]], shape=(2, 3, 4), dtype=float32)


In [7]:
# Import required packages
import tensorflow as tf
import keras
from keras.layers import Dense
#Create a sequential Model
model=keras.models.Sequential()
#Add input layer
model.add(Dense(5, input_shape=(8,), activation="relu"))
#Add Hidden Layer
model.add(Dense(3, activation="relu"))
#Add output layer
model.add(Dense(1, activation="sigmoid"))
#print model 
print(model.summary())



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 45        
                                                                 
 dense_1 (Dense)             (None, 3)                 18        
                                                                 
 dense_2 (Dense)             (None, 1)                 4         
                                                                 
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input_data, label, test_size=0.30, random_state=42)

In [9]:
# Compiling your previously built model
model.compile(optimizer="adam", loss="binary_crossentropy")
# Fit the model to the training data
model.fit(X_train, y_train, epochs=30)

Epoch 1/30
657/657 [==============================] - 1s 575us/step - loss: 1501.5425
Epoch 2/30
657/657 [==============================] - 0s 459us/step - loss: 48.9358
Epoch 3/30
657/657 [==============================] - 0s 452us/step - loss: 29.2627
Epoch 4/30
657/657 [==============================] - 0s 458us/step - loss: 22.5793
Epoch 5/30
657/657 [==============================] - 0s 460us/step - loss: 20.8855
Epoch 6/30
657/657 [==============================] - 0s 455us/step - loss: 23.6309
Epoch 7/30
657/657 [==============================] - 0s 456us/step - loss: 17.1142
Epoch 8/30
657/657 [==============================] - 0s 453us/step - loss: 17.1601
Epoch 9/30
657/657 [==============================] - 0s 453us/step - loss: 18.8080
Epoch 10/30
657/657 [==============================] - 0s 445us/step - loss: 18.1675
Epoch 11/30
657/657 [==============================] - 0s 452us/step - loss: 15.7576
Epoch 12/30
657/657 [==============================] - 0s 447us/step - l

In [30]:
X_train.shape

(21000, 8)

In [15]:
model.fit(input_data, label, epochs=30)

Epoch 1/30
938/938 [==============================] - 0s 471us/step - loss: 6.3752
Epoch 2/30
938/938 [==============================] - 0s 458us/step - loss: 5.5420
Epoch 3/30
938/938 [==============================] - 0s 458us/step - loss: 4.9926
Epoch 4/30
938/938 [==============================] - 0s 455us/step - loss: 4.6701
Epoch 5/30
938/938 [==============================] - 0s 453us/step - loss: 3.1219
Epoch 6/30
938/938 [==============================] - 0s 460us/step - loss: 1.9808
Epoch 7/30
938/938 [==============================] - 0s 461us/step - loss: 0.9144
Epoch 8/30
938/938 [==============================] - 0s 455us/step - loss: 0.7632
Epoch 9/30
938/938 [==============================] - 0s 457us/step - loss: 0.5895
Epoch 10/30
938/938 [==============================] - 0s 460us/step - loss: 0.5409
Epoch 11/30
938/938 [==============================] - 0s 464us/step - loss: 0.5357
Epoch 12/30
938/938 [==============================] - 0s 468us/step - loss: 0.5355
E

In [31]:
# Evaluate your results
model.evaluate(X_test, y_test)

282/282 [==============================] - 0s 371us/step - loss: 0.5242


0.5241618752479553

In [11]:
# Compiling your previously built model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy', 'AUC'])
#fit the model
model.fit(input_data, label, epochs=30, validation_split=0.20)
#evaluate
model.evaluate(X_test, y_test)

Epoch 1/30
750/750 [==============================] - 1s 801us/step - loss: 10.2345 - accuracy: 0.7007 - auc: 0.5800 - val_loss: 12.1893 - val_accuracy: 0.7952 - val_auc: 0.5562
Epoch 2/30
750/750 [==============================] - 0s 607us/step - loss: 8.6206 - accuracy: 0.7017 - auc: 0.5868 - val_loss: 3.9188 - val_accuracy: 0.8052 - val_auc: 0.6394
Epoch 3/30
750/750 [==============================] - 0s 619us/step - loss: 8.3665 - accuracy: 0.7028 - auc: 0.5814 - val_loss: 11.9510 - val_accuracy: 0.6045 - val_auc: 0.6050
Epoch 4/30
750/750 [==============================] - 0s 604us/step - loss: 9.0028 - accuracy: 0.6988 - auc: 0.5791 - val_loss: 6.2274 - val_accuracy: 0.2988 - val_auc: 0.5786
Epoch 5/30
750/750 [==============================] - 0s 608us/step - loss: 7.1874 - accuracy: 0.7031 - auc: 0.5936 - val_loss: 9.3691 - val_accuracy: 0.7960 - val_auc: 0.5582
Epoch 6/30
750/750 [==============================] - 0s 607us/step - loss: 8.5051 - accuracy: 0.7040 - auc: 0.5863 -

[4.907571792602539, 0.7865555286407471, 0.5749392509460449]