### Import the desired APIs

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Decalre a tensorflow constant and variable

In [7]:
# Declare a constant, we need to import constant from tensorflow
sample_constant=tf.constant(20)
print(sample_constant.dtype)
# Now we can perform some operations using tensorlfow in this constant
#Similarly, we can create variables also
A1=tf.Variable([1,2,3,4])
print(A1)
#Above created variable can be printed using the numpy conversion
print(A1.numpy())
B1=A1.numpy()

B1=tf.Variable(B1)
print(B1)

<dtype: 'int32'>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>
[1 2 3 4]
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>


### Operations on Tensor Constants and Variables

In [12]:
#Ones function
A1=tf.ones([3,2], tf.int32)
print(A1.numpy())

#Zeros function
B1=tf.zeros([3,2])
print(B1)

[[1 1]
 [1 1]
 [1 1]]
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [18]:
A1=tf.constant([1,2,3,4])
A23=tf.constant([[1,2,3], [4,5,6]])

#create ones tensor and perform element wise multiplication
B1=tf.ones_like(A1)
B23=tf.ones_like(A23)
C1=tf.multiply(A1,B1)
C23=tf.multiply(A23, B23)

#fill method
c33=tf.fill([3,3], 7)
print(c33.numpy())

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [19]:
# Matrix multiplication
#create feature value
feat_value=tf.constant([[1,12],[2,13],[3,14]])
parameters=tf.constant([[100],[200]])

#create predictions by matrix multiplication
pred=tf.matmul(feat_value, parameters)
print(pred)

# if we define actual value, we can have errors
actual=[[110], [120],[130]]
error=actual-pred
print(error)

tf.Tensor(
[[2500]
 [2800]
 [3100]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[-2390]
 [-2680]
 [-2970]], shape=(3, 1), dtype=int32)
tf.Tensor(8400, shape=(), dtype=int32)


### Reduce functions

In [21]:
#we can reduce the value of tensor
pred=tf.reduce_sum(pred)
print(pred)

#we can reduce at any dimension also
print(tf.reduce_sum(feat_value, 1))

tf.Tensor([13 15 17], shape=(3,), dtype=int32)


### reshape in tensorflow

In [26]:
#we need to reshape a picture so that it can be feed to neural network
#lets say we have a 28*28 grayscale image
image=tf.random.uniform([28,28], maxval=255, dtype='int32')
image_reshape=tf.reshape(image, [28*28,1])
#this is required when we input an image to the neural network

### Losses in Tensorflow

In [27]:
# Three losses most commonly used
#Mean Absolute Error
tf.keras.losses.mae()
#Mean squared error
tf.keras.losses.mse()
#Huber Error
tf.keras.losses.huber()

TypeError: Missing required positional argument

### Create a linear regression model

In [28]:
#import the dataset
housing=pd.read_csv('kc_house_data.csv')
housing.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [29]:
#Extract price and sqft for the dataset
price=np.array(housing['price'], np.float32)
size=np.array(housing['sqft_living'], np.float32)

#Lets define the intercept and slope of the linear regression
intercept=tf.Variable(0.1, np.float32)
slope=tf.Variable(0.1, np.float32)

In [33]:
#create a linear regression using y=mx+b
def linear_regression(intercept, slope, features=size):
    return slope*features+intercept

#create a loss function
def loss_function(intercept, slope, target=price, features=size):
    #create predictions
    pred=linear_regression(intercept, slope, features)
    loss= tf.keras.losses.mse(target, pred)
    return loss

#create an instance of optimizer
opt=tf.keras.optimizers.Adam()

#minimize the loss using epochs
epochs=1000
for i in range(epochs):
    opt.minimize(lambda: loss_function(intercept, slope), var_list=[intercept, slope])
    print(loss_function(intercept, slope))

tf.Tensor(425924620000.0, shape=(), dtype=float32)
tf.Tensor(425921940000.0, shape=(), dtype=float32)
tf.Tensor(425919150000.0, shape=(), dtype=float32)
tf.Tensor(425916470000.0, shape=(), dtype=float32)
tf.Tensor(425913750000.0, shape=(), dtype=float32)
tf.Tensor(425911060000.0, shape=(), dtype=float32)
tf.Tensor(425908300000.0, shape=(), dtype=float32)
tf.Tensor(425905620000.0, shape=(), dtype=float32)
tf.Tensor(425902900000.0, shape=(), dtype=float32)
tf.Tensor(425900100000.0, shape=(), dtype=float32)
tf.Tensor(425897430000.0, shape=(), dtype=float32)
tf.Tensor(425894700000.0, shape=(), dtype=float32)
tf.Tensor(425892020000.0, shape=(), dtype=float32)
tf.Tensor(425889330000.0, shape=(), dtype=float32)
tf.Tensor(425886550000.0, shape=(), dtype=float32)
tf.Tensor(425883860000.0, shape=(), dtype=float32)
tf.Tensor(425881080000.0, shape=(), dtype=float32)
tf.Tensor(425878360000.0, shape=(), dtype=float32)
tf.Tensor(425875640000.0, shape=(), dtype=float32)
tf.Tensor(425872950000.0, shape